import { pub, est } from '../lib.js';

// Cases, rackmount chassis and racks.
// The included fans' airflow/noise are not published on the pages that loaded,
// so each chassis's stock fans are modeled with the specs of a comparable fan
// from the catalog (estimate, flagged).

export const chassis = [
  {
    id: 'chs-hollow-quiet-xl', category: 'chassis', tier: 'consumer',
    displayName: 'Hollowform Quiet XL', realRef: 'Fractal Design Define 7 XL',
    formFactor: pub('tower', '', 'fractal-define7xl'),
    volumeL: pub(77.6, 'L', 'fractal-define7xl'),
    includedFans: pub(3, 'fans', 'fractal-define7xl', '3x 140 mm (2 front, 1 rear)'),
    includedFanSizeMm: pub(140, 'mm', 'fractal-define7xl'),
    includedFanModel: est('fan-sirocco-12q', '', 'Stock fan specs not published on the page; modeled as the quiet 120 mm catalog fan scaled by area (140/120)^2. Flagged.'),
    fanMounts: pub(11, 'mounts', 'fractal-define7xl', 'front 3x140, top 3x140, bottom 2x140, rear 1x140 (140 mm counts)'),
    maxGpuLengthMm: pub(530, 'mm', 'fractal-define7xl'),
    expansionSlots: pub(9, 'slots', 'fractal-define7xl'),
    driveBays35: pub(6, 'bays', 'fractal-define7xl', 'combined 3.5"/2.5" mounts as shipped; up to 18 HDDs with extra trays'),
    soundDamping: pub(true, 'bool', 'fractal-define7xl', '"industrial high-density sound damping"'),
    dampingDB: est(4, 'dB', 'No attenuation figure published. Assumed reduction in radiated noise from dense damping panels and a closed front. Flagged.'),
    dustFilters: est(true, 'bool', 'Define series ships with filters; not read on the page.'),
    priceUSD: est(250, 'USD', 'No price on the product page; assumed.'),
  },
  {
    id: 'chs-hollow-gale', category: 'chassis', tier: 'consumer',
    displayName: 'Hollowform Gale', realRef: 'Fractal Design Torrent',
    formFactor: pub('tower', '', 'fractal-torrent'),
    volumeL: pub(62.89, 'L', 'fractal-torrent'),
    includedFans: pub(5, 'fans', 'fractal-torrent', '2x 180 mm front, 3x 140 mm bottom'),
    includedFanSizeMm: est(160, 'mm', 'Mixed 180/140 mm stock fans; average size used for the area scaling.'),
    includedFanModel: est('fan-sirocco-12q', '', 'Stock fan specs not published on the page; modeled as the quiet 120 mm catalog fan scaled by area. Flagged.'),
    fanMounts: pub(7, 'mounts', 'fractal-torrent', 'front 3x140/2x180, bottom 3x140/2x180, rear 1x140'),
    maxGpuLengthMm: pub(461, 'mm', 'fractal-torrent'),
    expansionSlots: pub(7, 'slots', 'fractal-torrent'),
    driveBays35: est(2, 'bays', 'Not read on the page; assumed.'),
    soundDamping: est(false, 'bool', 'High-airflow open-front design; no damping listed.'),
    dampingDB: est(0, 'dB', 'No damping.'),
    dustFilters: pub(true, 'bool', 'fractal-torrent'),
    priceUSD: est(230, 'USD', 'No price on the product page; assumed.'),
  },
  {
    id: 'chs-hollow-r4', category: 'chassis', tier: 'server',
    displayName: 'Hollowform R4-12', realRef: 'Sliger CX4712',
    formFactor: pub('rack', '', 'sliger-cx4712'),
    rackUnits: pub(4, 'U', 'sliger-cx4712'),
    volumeL: est(48.6, 'L', 'Only depth (25" = 635 mm) is published on the page. Geometric volume: 4U height (177.8 mm) x typical 19" chassis body width (~430 mm, assumed) x 635 mm = 48.6 L.'),
    includedFans: est(0, 'fans', 'Included fans not stated on the page; assumed none included (fans bought separately).'),
    includedFanSizeMm: pub(120, 'mm', 'sliger-cx4712'),
    includedFanModel: est('fan-sirocco-12m', '', 'Mounts are 120 mm; high-pressure catalog fan used when the player adds fans.'),
    fanMounts: pub(7, 'mounts', 'sliger-cx4712', '3 or 6 mid-chassis, 1 rear exhaust'),
    maxGpuLengthMm: est(330, 'mm', 'Page states GPUs up to 158 mm tall but not max length; assumed from a 25" deep chassis minus drive cage.'),
    expansionSlots: pub(8, 'slots', 'sliger-cx4712'),
    driveBays35: pub(10, 'bays', 'sliger-cx4712', 'hot-swap'),
    soundDamping: est(false, 'bool', 'Rackmount chassis; no damping listed.'),
    dampingDB: est(0, 'dB', 'No damping.'),
    dustFilters: est(false, 'bool', 'Not listed.'),
    priceUSD: est(500, 'USD', 'No price on the product page; assumed.'),
  },
  {
    id: 'rack-hollow-42', category: 'rack', tier: 'datacenter',
    displayName: 'Hollowform Rack 42', realRef: 'APC NetShelter SX AR3100',
    rackUnits: pub(42, 'U', 'apc-ar3100'),
    heightMm: pub(1991, 'mm', 'apc-ar3100'), widthMm: pub(600, 'mm', 'apc-ar3100'), depthMm: pub(1070, 'mm', 'apc-ar3100'),
    doorsPerforated: est(true, 'bool', 'Perforation % not on the page; NetShelter SX doors are perforated for front-to-back airflow (assumed).'),
    priceUSD: est(1800, 'USD', 'No price on the product page; assumed.'),
  },
];
