import { pub, meas, est } from '../lib.js';

// GPUs. displayName values are PROPOSED fake brand names, pending user approval.
// Tensor TFLOPS/TOPS are dense (no sparsity). fp16TensorTflops is FP16 multiply
// with FP32 accumulate where the source distinguishes it; fp16AccTensorTflops is
// FP16 multiply with FP16 accumulate (twice the FP32-accumulate rate on GeForce,
// the same on professional/datacenter parts). fp32Tflops is non-tensor CUDA-core
// single precision.

const FE_GEFORCE_P2P = (card) =>
  est(false, 'bool', `GeForce cards: peer-to-peer over PCIe treated as unavailable. A search summary of nccl-tests issue #117 said "RTX 4090 does not support P2P by default"; applied to ${card} as well. Not confirmed on an opened page.`);

export const gpus = [
  {
    id: 'gpu-ember-g3-12', category: 'gpu', tier: 'consumer',
    displayName: 'Halcyon Ember G3-12', realRef: 'NVIDIA GeForce RTX 3060 12GB',
    vramGB: pub(12, 'GB', 'wiki-geforce30'),
    memBandwidthGBs: pub(360, 'GB/s', 'wiki-geforce30'),
    memType: pub('GDDR6', '', 'wiki-geforce30'),
    fp16TensorTflops: est(25.6, 'TFLOPS', 'Wikipedia lists 51.2 dense FP16 tensor TFLOPS (FP16 accumulate). On GeForce Ampere the FP32-accumulate rate is half of the FP16-accumulate rate (GA102 whitepaper: RTX 3090 142 vs 71), so 51.2 / 2.', 'wiki-geforce30'),
    fp16AccTensorTflops: pub(51.2, 'TFLOPS', 'wiki-geforce30', 'dense tensor compute column (FP16 accumulate)'),
    fp32Tflops: pub(12.74, 'TFLOPS', 'wiki-geforce30', 'single precision, boost'),
    int8TensorTops: est(102.4, 'TOPS', 'GeForce Ampere INT8 dense = 2x FP16-accumulate dense (GA102 whitepaper: RTX 3090 284 vs 142). 2 x 51.2.', 'wiki-geforce30'),
    boostClockMHz: pub(1777, 'MHz', 'wiki-geforce30'),
    boardPowerW: pub(170, 'W', 'wiki-geforce30'),
    idlePowerW: est(15, 'W', 'No idle figure found. RTX 4090 idle is 19 W (NVIDIA page); a smaller GA106 card is assumed a bit lower.'),
    maxTempC: est(93, 'C', 'No figure found for the 3060. Same Ampere generation as the RTX 3090, whose NVIDIA page lists 93 C.'),
    pcieGen: est(4, '', 'Ampere GeForce cards are PCIe 4.0 (GA102 whitepaper lists Gen 4 for GA102); assumed the same for GA106.'),
    pcieLanes: est(16, 'lanes', 'Full-length x16 card assumed.'),
    linkType: pub('none', '', 'wiki-geforce30', 'No NVLink on RTX 3060'),
    linkBandwidthGBs: pub(0, 'GB/s', 'wiki-geforce30'),
    p2pOverPcie: FE_GEFORCE_P2P('RTX 3060'),
    cooling: est('open-air', '', 'The 3060 12GB shipped as partner (AIB) cards with axial open-air coolers; no Founders Edition.'),
    slots: est(2, 'slots', 'Typical partner card width; no reference design.'),
    priceUSD: pub(283, 'USD', 'price-gp-3060', 'Sept 2026 lowest average price'),
  },
  {
    id: 'gpu-ember-g3-24', category: 'gpu', tier: 'consumer',
    displayName: 'Halcyon Ember G3-24 Link', realRef: 'NVIDIA GeForce RTX 3090',
    vramGB: pub(24, 'GB', 'nv-ga102-wp'),
    memBandwidthGBs: pub(936, 'GB/s', 'nv-ga102-wp'),
    memType: pub('GDDR6X', '', 'nv-ga102-wp'),
    fp16TensorTflops: pub(71, 'TFLOPS', 'nv-ga102-wp'),
    fp16AccTensorTflops: pub(142, 'TFLOPS', 'nv-ga102-wp'),
    fp32Tflops: pub(35.6, 'TFLOPS', 'nv-ga102-wp'),
    int8TensorTops: pub(284.7, 'TOPS', 'nv-bw-wp', 'Appendix A comparison column'),
    boostClockMHz: pub(1695, 'MHz', 'nv-ga102-wp'),
    boardPowerW: pub(350, 'W', 'nv-3090-page'),
    idlePowerW: est(20, 'W', 'No idle figure found. RTX 4090 idle is 19 W (NVIDIA page); GA102 with 24 GB GDDR6X assumed similar.'),
    maxTempC: pub(93, 'C', 'nv-3090-page'),
    pcieGen: pub(4, '', 'nv-bw-wp'),
    pcieLanes: est(16, 'lanes', 'Full-length card with an x16 edge connector (lane count not stated on the pages read).'),
    linkType: pub('nvlink', '', 'nv-3090-page', 'NVLink bridge, 2-way'),
    linkBandwidthGBs: pub(112.5, 'GB/s', 'nv-ga102-wp', '56.25 GB/s each direction, 112.5 total'),
    p2pOverPcie: FE_GEFORCE_P2P('RTX 3090'),
    cooling: est('open-air', '', 'Founders Edition uses two axial fans; heat goes into the case.'),
    slots: pub(3, 'slots', 'nv-3090-page'),
    priceUSD: pub(1355, 'USD', 'price-gp-3090', 'Sept 2026 lowest average price. PCSP used guide says $500-650: sources disagree.'),
  },
  {
    id: 'gpu-ember-g4-24', category: 'gpu', tier: 'consumer',
    displayName: 'Halcyon Ember G4-24', realRef: 'NVIDIA GeForce RTX 4090',
    vramGB: pub(24, 'GB', 'nv-ada-wp'),
    memBandwidthGBs: pub(1008, 'GB/s', 'nv-ada-wp'),
    memType: pub('GDDR6X', '', 'nv-ada-wp'),
    fp16TensorTflops: pub(165.2, 'TFLOPS', 'nv-ada-wp'),
    fp16AccTensorTflops: pub(330.3, 'TFLOPS', 'nv-ada-wp'),
    fp32Tflops: pub(82.6, 'TFLOPS', 'nv-ada-wp'),
    int8TensorTops: pub(660.6, 'TOPS', 'nv-ada-wp'),
    boostClockMHz: pub(2520, 'MHz', 'nv-ada-wp'),
    boardPowerW: pub(450, 'W', 'nv-4090-page'),
    idlePowerW: pub(19, 'W', 'nv-4090-page'),
    maxTempC: pub(90, 'C', 'nv-4090-page'),
    pcieGen: pub(4, '', 'nv-ada-wp'),
    pcieLanes: est(16, 'lanes', 'Full-length card with an x16 edge connector (lane count not stated on the pages read).'),
    linkType: pub('none', '', 'wiki-geforce40', 'No NVLink on RTX 40 series'),
    linkBandwidthGBs: pub(0, 'GB/s', 'wiki-geforce40'),
    p2pOverPcie: FE_GEFORCE_P2P('RTX 4090'),
    cooling: est('open-air', '', 'Founders Edition axial flow-through design; heat goes into the case.'),
    slots: pub(3, 'slots', 'nv-4090-page'),
    priceUSD: pub(2977, 'USD', 'price-gp-4090', 'Sept 2026 lowest average price'),
  },
  {
    id: 'gpu-ember-g5-32', category: 'gpu', tier: 'consumer',
    displayName: 'Halcyon Ember G5-32', realRef: 'NVIDIA GeForce RTX 5090',
    vramGB: pub(32, 'GB', 'nv-bw-wp'),
    memBandwidthGBs: pub(1792, 'GB/s', 'nv-bw-wp'),
    memType: pub('GDDR7', '', 'nv-bw-wp'),
    fp16TensorTflops: pub(209.5, 'TFLOPS', 'nv-bw-wp'),
    fp16AccTensorTflops: pub(419, 'TFLOPS', 'nv-bw-wp'),
    fp32Tflops: pub(104.8, 'TFLOPS', 'nv-bw-wp'),
    int8TensorTops: pub(838, 'TOPS', 'nv-bw-wp'),
    boostClockMHz: pub(2407, 'MHz', 'nv-bw-wp'),
    boardPowerW: pub(575, 'W', 'nv-5090-page'),
    idlePowerW: est(25, 'W', 'No idle figure found. RTX 4090 idle is 19 W; the larger GB202 with 32 GB GDDR7 assumed somewhat higher.'),
    maxTempC: pub(90, 'C', 'nv-5090-page'),
    pcieGen: pub(5, '', 'nv-bw-wp'),
    pcieLanes: pub(16, 'lanes', 'wiki-geforce50'),
    linkType: pub('none', '', 'wiki-geforce50'),
    linkBandwidthGBs: pub(0, 'GB/s', 'wiki-geforce50'),
    p2pOverPcie: FE_GEFORCE_P2P('RTX 5090'),
    cooling: est('flow-through', '', 'Founders Edition double flow-through with vapor chamber; heat goes into the case.'),
    slots: pub(2, 'slots', 'nv-5090-page'),
    priceUSD: pub(5409, 'USD', 'price-gp-5090', 'Sept 2026 lowest average price; MSRP was $1,999'),
  },
  {
    id: 'gpu-atelier-a48', category: 'gpu', tier: 'workstation',
    displayName: 'Halcyon Atelier A48', realRef: 'NVIDIA RTX A6000',
    vramGB: pub(48, 'GB', 'nv-ga102-wp'),
    memBandwidthGBs: pub(768, 'GB/s', 'nv-ga102-wp'),
    memType: pub('GDDR6', '', 'nv-ga102-wp'),
    fp16TensorTflops: pub(154.8, 'TFLOPS', 'nv-ga102-wp'),
    fp16AccTensorTflops: pub(154.8, 'TFLOPS', 'nv-ga102-wp'),
    fp32Tflops: pub(38.7, 'TFLOPS', 'nv-ga102-wp'),
    int8TensorTops: pub(309.7, 'TOPS', 'nv-ga102-wp'),
    boostClockMHz: pub(1800, 'MHz', 'nv-ga102-wp'),
    boardPowerW: pub(300, 'W', 'nv-a6000-page'),
    idlePowerW: est(20, 'W', 'No idle figure found; assumed similar to other GA102 boards.'),
    maxTempC: est(93, 'C', 'No figure found; assumed equal to the GA102-based RTX 3090 (93 C).'),
    pcieGen: pub(4, '', 'nv-a6000-page'),
    pcieLanes: pub(16, 'lanes', 'nv-a6000-page'),
    linkType: pub('nvlink', '', 'nv-a6000-page', '2-way bridge'),
    linkBandwidthGBs: pub(112, 'GB/s', 'nv-a6000-page'),
    p2pOverPcie: est(true, 'bool', 'Professional cards are assumed to allow PCIe peer-to-peer (not confirmed on an opened page).'),
    cooling: pub('blower', '', 'nv-a6000-page', 'Thermal: active; blower-style dual-slot card'),
    slots: pub(2, 'slots', 'nv-a6000-page'),
    priceUSD: est(5000, 'USD', 'A new PNY listing at $4,999 was only seen in a search snippet (page returned 403); used listings in snippets were $4,310-$8,900.'),
  },
  {
    id: 'gpu-atelier-b96', category: 'gpu', tier: 'workstation',
    displayName: 'Halcyon Atelier B96', realRef: 'NVIDIA RTX PRO 6000 Blackwell Workstation Edition',
    vramGB: pub(96, 'GB', 'nv-pro6000-page'),
    memBandwidthGBs: pub(1792, 'GB/s', 'nv-pro6000-page'),
    memType: pub('GDDR7', '', 'nv-pro6000-page'),
    fp16TensorTflops: pub(503.8, 'TFLOPS', 'nv-bwpro-wp'),
    fp16AccTensorTflops: pub(503.8, 'TFLOPS', 'nv-bwpro-wp'),
    fp32Tflops: pub(126.0, 'TFLOPS', 'nv-bwpro-wp'),
    int8TensorTops: pub(1007.6, 'TOPS', 'nv-bwpro-wp'),
    boostClockMHz: pub(2617, 'MHz', 'nv-bwpro-wp'),
    boardPowerW: pub(600, 'W', 'nv-pro6000-page'),
    idlePowerW: est(30, 'W', 'No idle figure found; assumed above the RTX 4090 idle (19 W) for a 600 W board with 96 GB GDDR7.'),
    maxTempC: est(90, 'C', 'No figure found; assumed equal to the same-die RTX 5090 (90 C).'),
    pcieGen: pub(5, '', 'nv-bwpro-wp'),
    pcieLanes: est(16, 'lanes', 'Full-length card with an x16 edge connector (lane count not stated on the pages read).'),
    linkType: est('none', '', 'No NVLink mentioned on the product page.'),
    linkBandwidthGBs: est(0, 'GB/s', 'No NVLink.'),
    p2pOverPcie: est(true, 'bool', 'Professional cards are assumed to allow PCIe peer-to-peer (not confirmed on an opened page).'),
    cooling: pub('flow-through', '', 'nv-pro6000-page', 'Double Flow Through'),
    slots: pub(2, 'slots', 'nv-pro6000-page'),
    priceUSD: pub(16000, 'USD', 'price-thunder-pro6000', 'MSRP was $8,565'),
  },
  {
    id: 'gpu-bastion-p48', category: 'gpu', tier: 'datacenter',
    displayName: 'Halcyon Bastion P48', realRef: 'NVIDIA L40S',
    vramGB: pub(48, 'GB', 'nv-l40s-page'),
    memBandwidthGBs: pub(864, 'GB/s', 'nv-l40s-page'),
    memType: pub('GDDR6', '', 'nv-l40s-page'),
    fp16TensorTflops: pub(362.05, 'TFLOPS', 'nv-l40s-page', 'BF16/FP16 tensor, dense'),
    fp16AccTensorTflops: est(362.05, 'TFLOPS', 'NVIDIA lists one BF16/FP16 tensor figure without the accumulate type; datacenter Ada runs FP32 accumulate at full rate (RTX 6000 Ada: 364 either way), so the same figure is used.', 'nv-l40s-page'),
    fp32Tflops: pub(91.6, 'TFLOPS', 'nv-l40s-page'),
    int8TensorTops: pub(733, 'TOPS', 'nv-l40s-page', 'dense'),
    boostClockMHz: est(2490, 'MHz', 'L40S clock not found; the L40 (same AD102 core configuration) lists 2490 MHz max boost on Wikipedia.', 'wiki-nv-dc'),
    boardPowerW: pub(350, 'W', 'nv-l40s-page'),
    idlePowerW: est(30, 'W', 'No idle figure found; assumed for a 350 W datacenter board.'),
    maxTempC: est(88, 'C', 'No figure found; passive datacenter card assumed to throttle a little below GeForce Ada (90 C).'),
    pcieGen: pub(4, '', 'nv-l40s-page'),
    pcieLanes: pub(16, 'lanes', 'nv-l40s-page'),
    linkType: pub('none', '', 'nv-l40s-page', 'NVLink: No'),
    linkBandwidthGBs: pub(0, 'GB/s', 'nv-l40s-page'),
    p2pOverPcie: est(true, 'bool', 'Datacenter cards are assumed to allow PCIe peer-to-peer (not confirmed on an opened page).'),
    cooling: pub('passive', '', 'nv-l40s-page'),
    slots: pub(2, 'slots', 'nv-l40s-page'),
    priceUSD: pub(8000, 'USD', 'price-pcsp-2026', 'Midpoint of the $7,000-9,000 used range'),
  },
  {
    id: 'gpu-bastion-h80', category: 'gpu', tier: 'datacenter',
    displayName: 'Halcyon Bastion H80', realRef: 'NVIDIA A100 80GB PCIe',
    vramGB: pub(80, 'GB', 'nv-a100-page'),
    memBandwidthGBs: pub(1935, 'GB/s', 'nv-a100-page'),
    memType: pub('HBM2e', '', 'nv-a100-page'),
    fp16TensorTflops: pub(312, 'TFLOPS', 'nv-a100-page', 'dense'),
    fp16AccTensorTflops: pub(312, 'TFLOPS', 'nv-a100-page', 'A100 has one FP16 tensor rate'),
    fp32Tflops: pub(19.5, 'TFLOPS', 'nv-a100-page'),
    int8TensorTops: pub(624, 'TOPS', 'nv-a100-page', 'dense'),
    boostClockMHz: pub(1410, 'MHz', 'wiki-nv-dc'),
    boardPowerW: pub(300, 'W', 'nv-a100-page'),
    idlePowerW: est(40, 'W', 'No idle figure found; assumed for an HBM2e datacenter board.'),
    maxTempC: est(85, 'C', 'No figure found; passive datacenter card assumed to throttle at 85 C.'),
    pcieGen: pub(4, '', 'nv-a100-page'),
    pcieLanes: est(16, 'lanes', 'PCIe Gen4 64 GB/s bidirectional implies x16.', 'nv-a100-page'),
    linkType: pub('nvlink', '', 'nv-a100-page', 'NVLink bridge for 2 GPUs'),
    linkBandwidthGBs: pub(600, 'GB/s', 'nv-a100-page'),
    p2pOverPcie: est(true, 'bool', 'Datacenter cards are assumed to allow PCIe peer-to-peer.'),
    cooling: est('passive', '', 'NVIDIA lists "PCIe dual-slot air-cooled": a heatsink that relies on server chassis airflow.', 'nv-a100-page'),
    slots: pub(2, 'slots', 'nv-a100-page'),
    priceUSD: pub(10000, 'USD', 'price-jarvis-a100', 'Midpoint of the $8,000-12,000 new range (March 2026)'),
  },
  {
    id: 'gpu-bastion-x94', category: 'gpu', tier: 'datacenter',
    displayName: 'Halcyon Bastion X94', realRef: 'NVIDIA H100 NVL',
    vramGB: pub(94, 'GB', 'nv-h100-page'),
    memBandwidthGBs: pub(3900, 'GB/s', 'nv-h100-page'),
    memType: pub('HBM3', '', 'nv-h100-page'),
    fp16TensorTflops: est(835.5, 'TFLOPS', 'NVIDIA lists 1,671 TFLOPS with sparsity; dense is half, as on every other SKU in these tables.', 'nv-h100-page'),
    fp16AccTensorTflops: est(835.5, 'TFLOPS', 'Same as the FP16 tensor figure: Hopper has one FP16 tensor rate. 1,671 with sparsity / 2.', 'nv-h100-page'),
    fp32Tflops: pub(60, 'TFLOPS', 'nv-h100-page'),
    int8TensorTops: est(1670.5, 'TOPS', 'NVIDIA lists 3,341 TOPS with sparsity; dense is half.', 'nv-h100-page'),
    boostClockMHz: est(1785, 'MHz', 'Not found on an opened page. Wikipedia lists H100 PCIe at 1755 MHz and SXM at 1980 MHz; NVL placed between them.', 'wiki-nv-dc'),
    boardPowerW: pub(400, 'W', 'nv-h100-page', 'Configurable 350-400 W; top of range used'),
    idlePowerW: est(50, 'W', 'No idle figure found; assumed for an HBM3 datacenter board.'),
    maxTempC: est(85, 'C', 'No figure found; passive datacenter card assumed to throttle at 85 C.'),
    pcieGen: pub(5, '', 'nv-h100-page'),
    pcieLanes: est(16, 'lanes', 'PCIe Gen5 128 GB/s bidirectional implies x16.', 'nv-h100-page'),
    linkType: pub('nvlink', '', 'nv-h100-page', 'NVLink bridge'),
    linkBandwidthGBs: pub(600, 'GB/s', 'nv-h100-page'),
    p2pOverPcie: est(true, 'bool', 'Datacenter cards are assumed to allow PCIe peer-to-peer.'),
    cooling: est('passive', '', 'NVIDIA lists "PCIe dual-slot air-cooled": relies on server chassis airflow.', 'nv-h100-page'),
    slots: pub(2, 'slots', 'nv-h100-page'),
    priceUSD: est(30000, 'USD', 'No NVL-specific price found. compute.exchange gives $25k-40k new for the 80GB class with PCIe at the low end; CloudZero gives ~$31k for a new 80GB card.', 'price-cx-h100'),
  },
];

// Hardware that appears in calibration benchmarks but is not sold in the game.
// Dev-only: used by scripts/calibrate.js, never shipped.
export const calibrationGpus = [
  {
    id: 'cal-a100-sxm', category: 'gpu', tier: 'datacenter', displayName: 'calibration-only A100 SXM', realRef: 'NVIDIA A100 80GB SXM',
    vramGB: pub(80, 'GB', 'nv-a100-page'), memBandwidthGBs: pub(2039, 'GB/s', 'nv-a100-page'), memType: pub('HBM2e', '', 'nv-a100-page'),
    fp16TensorTflops: pub(312, 'TFLOPS', 'nv-a100-page'), int8TensorTops: pub(624, 'TOPS', 'nv-a100-page'),
    fp16AccTensorTflops: pub(312, 'TFLOPS', 'nv-a100-page'), fp32Tflops: pub(19.5, 'TFLOPS', 'nv-a100-page'),
    boostClockMHz: pub(1410, 'MHz', 'wiki-nv-dc', 'PCIe card clock; SXM assumed the same'),
    boardPowerW: pub(400, 'W', 'nv-a100-page'), idlePowerW: est(50, 'W', 'Calibration-only part; idle power not needed for calibration and not researched.'), maxTempC: est(85, 'C', 'Calibration-only part; throttle temperature not needed for calibration.'),
    pcieGen: pub(4, '', 'nv-a100-page'), pcieLanes: est(16, 'lanes', 'SXM module host link treated as x16 (calibration-only part).'),
    linkType: pub('nvlink', '', 'nv-a100-page'), linkBandwidthGBs: pub(600, 'GB/s', 'nv-a100-page'),
    p2pOverPcie: est(true, 'bool', 'Datacenter.'), cooling: est('passive', '', 'SXM module.'), slots: est(0, 'slots', 'SXM module.'),
    priceUSD: est(0, 'USD', 'Not sold in game.'),
  },
  {
    id: 'cal-h100-sxm', category: 'gpu', tier: 'datacenter', displayName: 'calibration-only H100 SXM', realRef: 'NVIDIA H100 SXM5 80GB',
    vramGB: pub(80, 'GB', 'nv-h100-page'), memBandwidthGBs: pub(3350, 'GB/s', 'nv-h100-page'), memType: pub('HBM3', '', 'nv-h100-page'),
    fp16TensorTflops: est(989.5, 'TFLOPS', '1,979 with sparsity / 2.', 'nv-h100-page'), int8TensorTops: est(1979, 'TOPS', '3,958 with sparsity / 2.', 'nv-h100-page'),
    fp16AccTensorTflops: est(989.5, 'TFLOPS', '1,979 with sparsity / 2; one FP16 tensor rate.', 'nv-h100-page'), fp32Tflops: pub(67, 'TFLOPS', 'nv-h100-page'),
    boostClockMHz: pub(1980, 'MHz', 'wiki-nv-dc'),
    boardPowerW: pub(700, 'W', 'nv-h100-page'), idlePowerW: est(70, 'W', 'Calibration-only part; idle power not needed for calibration and not researched.'), maxTempC: est(85, 'C', 'Calibration-only part; throttle temperature not needed for calibration.'),
    pcieGen: pub(5, '', 'nv-h100-page'), pcieLanes: est(16, 'lanes', 'SXM module host link treated as x16 (calibration-only part).'),
    linkType: pub('nvlink', '', 'nv-h100-page'), linkBandwidthGBs: pub(900, 'GB/s', 'nv-h100-page'),
    p2pOverPcie: est(true, 'bool', 'Datacenter.'), cooling: est('passive', '', 'SXM module.'), slots: est(0, 'slots', 'SXM module.'),
    priceUSD: est(0, 'USD', 'Not sold in game.'),
  },
];
