import { pub, meas, est } from '../lib.js';

// Storage. afrDatasheet is the manufacturer rating; afrField is a real fleet
// measurement where one exists (Backblaze).

export const storages = [
  {
    id: 'sto-strata-nova-2', category: 'storage', tier: 'consumer',
    displayName: 'Strata Nova 2TB', realRef: 'Samsung 990 PRO 2TB',
    kind: pub('nvme-ssd', '', 'ds-990pro'), interface: pub('PCIe 4.0 x4 NVMe', '', 'ds-990pro'),
    capacityTB: pub(2, 'TB', 'ds-990pro'),
    seqReadMBs: pub(7450, 'MB/s', 'ds-990pro'), seqWriteMBs: pub(6900, 'MB/s', 'ds-990pro'),
    randReadIopsQD1: pub(22000, 'IOPS', 'ds-990pro'), randWriteIopsQD1: pub(80000, 'IOPS', 'ds-990pro'),
    randReadIopsHighQD: pub(1400000, 'IOPS', 'ds-990pro', 'QD32 T16'), randWriteIopsHighQD: pub(1550000, 'IOPS', 'ds-990pro', 'QD32 T16'),
    activePowerW: pub(5.8, 'W', 'ds-990pro', 'read average'), idlePowerW: pub(0.055, 'W', 'ds-990pro', 'APST on'),
    endurance: pub(1200, 'TBW', 'ds-990pro'),
    mtbfHours: pub(1500000, 'h', 'ds-990pro'),
    maxOperatingTempC: pub(70, 'C', 'ds-990pro'),
    uberBits: est(1e17, 'bits', 'SSD unrecoverable bit error rate not in the datasheet; consumer TLC SSDs are commonly specified at 1 per 10^15 to 10^17. Upper value used; flagged.'),
    priceUSD: pub(389.99, 'USD', 'price-mmb-990pro'),
  },
  {
    id: 'sto-strata-vault-3t8', category: 'storage', tier: 'server',
    displayName: 'Strata Vault 3.84TB U.3', realRef: 'Micron 7450 PRO 3.84TB U.3',
    kind: pub('nvme-ssd', '', 'ds-micron7450'), interface: pub('PCIe 4.0 x4 NVMe U.3', '', 'ds-micron7450'),
    capacityTB: pub(3.84, 'TB', 'ds-micron7450'),
    seqReadMBs: pub(6800, 'MB/s', 'ds-micron7450'), seqWriteMBs: pub(5600, 'MB/s', 'ds-micron7450'),
    randReadIopsQD1: est(15000, 'IOPS', 'QD1 figure not in the brief; assumed below the consumer 990 PRO QD1 figure (22K) because enterprise drives are tuned for high queue depth.'),
    randWriteIopsQD1: est(50000, 'IOPS', 'QD1 figure not in the brief; assumed.'),
    randReadIopsHighQD: pub(1000000, 'IOPS', 'ds-micron7450', 'QD256, 4K'), randWriteIopsHighQD: pub(180000, 'IOPS', 'ds-micron7450', 'PRO, QD128'),
    activePowerW: est(14, 'W', 'Active power not in the product brief; assumed for a U.3 enterprise NVMe drive.'),
    idlePowerW: est(5, 'W', 'Idle power not in the product brief; assumed for a U.3 enterprise NVMe drive.'),
    endurance: pub(7008, 'TBW', 'price-dcd-7450', '1 DWPD'),
    mtbfHours: est(2000000, 'h', 'MTTF not in the product brief; assumed at a typical enterprise SSD rating.'),
    maxOperatingTempC: est(70, 'C', 'Not in the brief; assumed.'),
    uberBits: est(1e17, 'bits', 'Not in the brief; enterprise SSDs are commonly specified at 1 per 10^17. Flagged.'),
    priceUSD: pub(1990, 'USD', 'price-dcd-7450', 'Refurbished; no new listing available'),
  },
  {
    id: 'sto-lodestone-x24', category: 'storage', tier: 'server',
    displayName: 'Lodestone X 24TB', realRef: 'Seagate Exos X24 24TB SATA (ST24000NM002H)',
    kind: pub('hdd', '', 'ds-exosx24'), interface: pub('SATA 6Gb/s', '', 'ds-exosx24'),
    capacityTB: pub(24, 'TB', 'ds-exosx24'),
    rpm: pub(7200, 'rpm', 'ds-exosx24'),
    seqReadMBs: pub(285, 'MB/s', 'ds-exosx24'), seqWriteMBs: pub(285, 'MB/s', 'ds-exosx24'),
    randReadIopsHighQD: pub(168, 'IOPS', 'ds-exosx24', '4K QD16'), randWriteIopsHighQD: pub(550, 'IOPS', 'ds-exosx24', '4K QD16, write cache disabled'),
    randReadIopsQD1: est(80, 'IOPS', 'QD1 not in the datasheet; for a 7200 rpm drive the average rotational latency is 4.17 ms plus seek, giving roughly 80 IOPS.'),
    randWriteIopsQD1: est(80, 'IOPS', 'Same mechanical limit as QD1 reads (seek + rotational latency); drive write cache ignored.'),
    activePowerW: pub(8.9, 'W', 'ds-exosx24', 'Max operating, random read 4K/16Q'), idlePowerW: pub(6.3, 'W', 'ds-exosx24', 'Idle A average'),
    mtbfHours: pub(2500000, 'h', 'ds-exosx24'),
    afrDatasheet: pub(0.35, '%/yr', 'ds-exosx24'),
    afrField: meas(2.89, '%/yr', 'bb-q1-2026', 'Backblaze lifetime AFR for ST24000NM002H, 9,605 drives'),
    uberBits: pub(1e15, 'bits', 'ds-exosx24', '<1 in 10^15 bits read'),
    maxOperatingTempC: pub(60, 'C', 'ds-exosx24'),
    priceUSD: pub(750, 'USD', 'price-diskprices-exos', 'Renewed listing'),
  },
  {
    id: 'sto-lodestone-nas8', category: 'storage', tier: 'consumer',
    displayName: 'Lodestone NAS 8TB', realRef: 'WD Red Plus 8TB (WD80EFPX)',
    kind: pub('hdd', '', 'ds-wdredplus'), interface: pub('SATA 6Gb/s', '', 'ds-wdredplus'),
    capacityTB: pub(8, 'TB', 'ds-wdredplus'),
    rpm: pub(5640, 'rpm', 'ds-wdredplus'),
    seqReadMBs: pub(215, 'MB/s', 'ds-wdredplus'), seqWriteMBs: pub(215, 'MB/s', 'ds-wdredplus'),
    randReadIopsQD1: est(60, 'IOPS', 'Not in the datasheet; 5640 rpm gives ~5.3 ms average rotational latency plus seek, roughly 60 IOPS.'),
    randWriteIopsQD1: est(60, 'IOPS', 'Same mechanical limit as QD1 reads (seek + rotational latency); drive write cache ignored.'),
    randReadIopsHighQD: est(120, 'IOPS', 'Not in the datasheet; scaled from the Exos 7200 rpm QD16 read figure by rpm ratio.'),
    randWriteIopsHighQD: est(120, 'IOPS', 'Not in the datasheet; assumed equal to reads.'),
    activePowerW: pub(5.2, 'W', 'ds-wdredplus', 'Read/write average'), idlePowerW: pub(3.4, 'W', 'ds-wdredplus'),
    mtbfHours: pub(1000000, 'h', 'ds-wdredplus'),
    workloadTBperYear: pub(180, 'TB/yr', 'ds-wdredplus'),
    uberBits: pub(1e14, 'bits', 'ds-wdredplus', '<1 in 10^14 bits read'),
    maxOperatingTempC: pub(65, 'C', 'ds-wdredplus'),
    priceUSD: pub(354.99, 'USD', 'price-mmb-wdred8', 'Newegg'),
  },
];
