// GENERATED by `npm run calibrate -- --fit` on 2026-09-30. Do not edit by hand.
// Every value is an estimate fitted to published benchmarks (see reasoning).
import { est } from './lib.js';

export const fittedPerf = {
  'eng-kettle': {
    bwEfficiency: est(0.914, 'fraction', "Fitted by scripts/calibrate.js --fit to 6 published cases (A-3060-tg, A-3090-tg, A-4090-tg, A-5090-tg, A-a6000-tg, A-pro6000-tg); in-sample RMS error 2.9% (log-space)."),
    layerOverheadCycles: est(89000, 'cycles', "Fitted by scripts/calibrate.js --fit to 6 published cases (A-3060-tg, A-3090-tg, A-4090-tg, A-5090-tg, A-a6000-tg, A-pro6000-tg); in-sample RMS error 2.9% (log-space)."),
    prefillEfficiencyQuant: est(2.31, 'x fp32Tflops', "Fitted by scripts/calibrate.js --fit to 8 published cases (A-3060-pp, A-3090-pp, A-4090-pp, A-5090-pp, A-a6000-pp, A-pro6000-pp, A-a100-pp, A-h100sxm-pp); in-sample RMS error 22.0% (log-space)."),
    prefillEfficiencyFp16: est(0.4, 'fraction', "Fitted by scripts/calibrate.js --fit to 4 published cases (B-3090-8bf16-pp, B-4090-8bf16-pp, B-a6000-8bf16-pp, B-a100-8bf16-pp); in-sample RMS error 6.8% (log-space)."),
    moeLayerOverheadCycles: est(146000, 'cycles', "Fitted by scripts/calibrate.js --fit to 1 published cases (C-4090-oss20-tg); in-sample RMS error 0.2% (log-space)."),
    moePrefillFactor: est(0.275, 'fraction', "Fitted by scripts/calibrate.js --fit to 1 published cases (C-4090-oss20-pp); in-sample RMS error 0.2% (log-space)."),
    seqLayerOverheadUs: est(14.05, 'us', "Fitted by scripts/calibrate.js --fit to 3 published cases (D-4090-lcpp-64, D-l40s-lcpp-64, D-5090-lcpp-64); in-sample RMS error 16.0% (log-space)."),
    hbmBwFactor: est(0.59, 'fraction', "Fitted by scripts/calibrate.js --fit to 4 published cases (A-a100-tg, A-h100sxm-tg, I-h100p-8b, I-h100p-8bf16); in-sample RMS error 11.2% (log-space)."),
  },
  'eng-sluice': {
    bwEfficiency: est(1, 'fraction', "Fitted by scripts/calibrate.js --fit to 3 published cases (D-4090-vllm-1, D-l40s-vllm-1, D-5090-vllm-1); in-sample RMS error 4.9% (log-space)."),
    layerOverheadCycles: est(88000, 'cycles', "Fitted by scripts/calibrate.js --fit to 3 published cases (D-4090-vllm-1, D-l40s-vllm-1, D-5090-vllm-1); in-sample RMS error 4.9% (log-space)."),
    prefillEfficiencyQuant: est(2.31, 'x fp32Tflops', "No vLLM data for this constant; set equal to the fitted llama.cpp value."),
    prefillEfficiencyFp16: est(0.74, 'fraction', "Fitted by scripts/calibrate.js --fit to 3 published cases (D-4090-vllm-64, D-l40s-vllm-64, D-5090-vllm-64); in-sample RMS error 2.7% (log-space)."),
    moeLayerOverheadCycles: est(146000, 'cycles', "No vLLM data for this constant; set equal to the fitted llama.cpp value."),
    moePrefillFactor: est(0.275, 'fraction', "No vLLM data for this constant; set equal to the fitted llama.cpp value."),
    seqLayerOverheadUs: est(0.5, 'us', "Fitted by scripts/calibrate.js --fit to 3 published cases (D-4090-vllm-64, D-l40s-vllm-64, D-5090-vllm-64); in-sample RMS error 2.7% (log-space)."),
    hbmBwFactor: est(1, 'fraction', 'No single-stream vLLM decode data on HBM cards in the fit set; not applied (1). The held-out A100 SXM vLLM cases (set E) check this.'),
  },
  'eng-loom': {
    bwEfficiency: est(1, 'fraction', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    layerOverheadCycles: est(88000, 'cycles', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    prefillEfficiencyQuant: est(2.31, 'x fp32Tflops', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    prefillEfficiencyFp16: est(0.74, 'fraction', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    moeLayerOverheadCycles: est(146000, 'cycles', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    moePrefillFactor: est(0.275, 'fraction', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    seqLayerOverheadUs: est(0.5, 'us', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
    hbmBwFactor: est(0.59, 'fraction', "No SGLang benchmark on catalog hardware was found; set equal to the fitted vLLM value (or llama.cpp where vLLM had no data)."),
  },
};
